### ISSUE TITLE
Error occurred 'str' object has no attribute 'get_channel_audio_data'

### ISSUE THREAD

**Issue by hamster-poodle** [a1lazydog/ComfyUI-AudioScheduler#12]
Both wav and mp3 files can't be loaded.

Error occurred when executing AudioToFFTs:
'str' object has no attribute 'get_channel_audio_data'

**Comment by H445** [comment]
I encountered the same issue, seems to be due to conflicting Nodes in "[ComfyUI-UVR5]". Disabling the conflicting package seems to have resolved.

**Comment by a1lazydog** [comment]
This should now be resolved on the latest
