### ISSUE TITLE
'str' object has no attribute 'get_channel_fft'

### ISSUE THREAD

**Issue by xxinlei** [a1lazydog/ComfyUI-AudioScheduler#21]
How can I fix this?

```
2024-06-14 23:56:30,515- root:179- ERROR- !!! Exception during processing!!! 'str' object has no attribute 'get_channel_fft'
2024-06-14 23:56:30,515- root:180- ERROR- Traceback (most recent call last):
  File "D:\User\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AudioScheduler\nodes.py", line 177, in fft
    audio_fft = audio.get_channel_fft(channel)
                ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_channel_fft'
```

**Comment by lovisdotio** [comment]
kind of the same 
AttributeError: 'dict' object has no attribute 'get_channel_fft'

**Comment by WilliamStanford** [comment]
> kind of the same AttributeError: 'dict' object has no attribute 'get_channel_fft'

Work around I found, use the "Load Audio (Path) VHS" node, connect it to the new node in this package "Load VHS Audio", then use the output of this node in place of whatever you were using audio with before

**Comment by garland92** [comment]
> > kind of the same AttributeError: 'dict' object has no attribute 'get_channel_fft'
> 
> Work around I found, use the "Load Audio (Path) VHS" node, connect it to the new node in this package "Load VHS Audio", then use the output of this node in place of whatever you were using audio with before

[workflow-audio-reactive-prompt-scheduling.json](https://github.com/user-attachments/files/16355916/workflow-audio-reactive-prompt-scheduling.json)

Nice, it works like a charm!

**Comment by a1lazydog** [comment]
Updated to support LoadAudio instead of having a custom one
