### ISSUE TITLE
Where did LoadVHSAudio go?

### ISSUE THREAD

**Issue by arlechinu** [a1lazydog/ComfyUI-AudioScheduler#27]
Hi!

I was using your awesome nodes for a while now but updated a new install and realized the LoadVHSAudio node is now gone? I took the liberty of pasting back the class from the old version and it works fine but was wondering why it was gone and if you could add it back? :)

Cheers!

**Comment by a1lazydog** [comment]
`LoadVHSAudio` is replaced by `AudioToAudioData `node.  This new node can take the audio from either the built in or the VHS LoadAudio node and convert it correctly

**Comment by arlechinu** [comment]
I know, been using the new node and it works fine. Except the issue is I was using the old node to also output the audio to a deforum video save node. The new node gives out errors when trying to connect the audio to the save video node. For some reason I can’t make any other node work to get the sound into the end video, except your old LoadVHSAudio :D
